=== noahpetrucci/IST311FinalProject-master/IST311FinalProject-master/Manager.dtd
<!ELEMENT managerRecords (Manager*)>
<!ELEMENT Manager (Id,username,password)>
<!ELEMENT  Id (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>

=== noahpetrucci/IST311FinalProject-master/IST311FinalProject-master/ManagerXML.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE managerRecords SYSTEM "Manager.dtd">
<managerRecords>
    <Manager>
        <Id>1</Id>
        <username>steve</username>
        <password>jobs</password>
    </Manager>
    <Manager>
        <Id>2</Id>
        <username>prez</username>
        <password>password6</password>
    </Manager>
    <Manager>
        <Id>3</Id>
        <username>datdude555</username>
        <password>password555</password>
    </Manager>
</managerRecords>
